import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Aside from "@/components/Aside";
import { Search } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${
          geistSans.variable} ${geistMono.variable} antialiased
          grid grid-cols-[320px_1fr]
        `}
      >
        <Aside />
        <main className="flex flex-col items-center py-8 gap-8">
          <div className="relative flex items-center">
            <Search
              strokeWidth={1}
              size={20}
              className="absolute left-2"
            />
            <input
              type="text"
              placeholder="¿Qué Deseas Aprender Hoy?"
              className="bg-transparent border-2 border-neutral-600 rounded-lg pl-8 pr-2 py-1.5 w-[800px]"
            />
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}